### ISSUE TITLE
[Question] RAM usage

### ISSUE THREAD

**Issue by msmcconnell** [1hada/rosbag-merge#7]
Does this load the rosbag fully into RAM memory?
I am getting out of memory errors while running it on a machine with 16 GB of ram which is getting close to the rosbag sizes.

**Comment by 1hada** [comment]
@msmcconnell , I asked the [rosbags developers](https://gitlab.com/ternaris/rosbags/-/issues/82) and they have 2 ideas one what the issue may be. They also did confirm that the rosbag index gets loaded unto ram. 
Note in my implementation I closely followed rosbags reading mechanisms and used yield in order to prevent unnecessary RAM usage. I do use `tqdm` because it's nice to have a progress bar, though that also shouldn't be loading everything to ram.

Have you tried splitting the large rosbags into smaller files and seeing if that helps? I'd be interested to know if that helps.

**Comment by 1hada** [comment]
@msmcconnell , I beleive @PushyamiKaveti solved the issue with https://github.com/1hada/rosbag-merge/pull/8
